/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nikola1998 (https://sketchfab.com/Nikola1998)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-eagle-60578c2b11064a2da915ea899614b0b8
Title: Low Poly Eagle
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

import eagle from '../assets/3d/eagle.glb';

export function Eagle(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(eagle);
  const { actions } = useAnimations(animations, group);

  useFrame(({clock, camera}) => {
    group.current.position.y = Math.sin(clock.elapsedTime) * 0.2 + 2;

    if(group.current.position.x > camera.position.x + 10){
        group.current.rotation.y = Math.PI;
    } else if (group.current.position.x < camera.position.x - 10) {
        group.current.rotation.y = 0;
    }

    if(group.current.rotation.y === 0){
        group.current.position.x += 0.01;
        group.current.position.z -= 0.01;
    } else {
        group.current.position.x -= 0.01;
        group.current.position.z += 0.01;
    }
  });


  useEffect(() => {
    actions['Breeze'].play();
  },[]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 40]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Armature_14"
                position={[0, 1.156, -1.175]}
                rotation={[1.619, 0, 0]}
                scale={0.852}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Material}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Eagle_13" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eagle.glb')