/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tiikeri (https://sketchfab.com/tiikeri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-hurt-c624cad7e0e04960a66f619270eec8f3
Title: Fox Hurt
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from "../assets/3d/foxie.glb"

export function Foxie({currentAnimation , ...props}) {

  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['Scene'].play();
  },[]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="4e9bd9cf27eb4013ad4b7511029335ecfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Armature003"
                  position={[-1.157, 0, 2.183]}
                  rotation={[Math.PI, -1.352, Math.PI]}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_45"
                      geometry={nodes.Object_45.geometry}
                      material={materials.BrownFur}
                      skeleton={nodes.Object_45.skeleton}
                    />
                    <skinnedMesh
                      name="Object_46"
                      geometry={nodes.Object_46.geometry}
                      material={materials.RedFur}
                      skeleton={nodes.Object_46.skeleton}
                    />
                    <skinnedMesh
                      name="Object_47"
                      geometry={nodes.Object_47.geometry}
                      material={materials.WhiteFur}
                      skeleton={nodes.Object_47.skeleton}
                    />
                    <group
                      name="Object_44"
                      position={[3.788, 0.443, -7.029]}
                      rotation={[-Math.PI / 2, 0, 2.923]}
                    />
                  </group>
                </group>
                <group
                  name="Fox_Copy003"
                  position={[3.788, 0.443, -7.029]}
                  rotation={[-Math.PI / 2, 0, 2.923]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/foxie.glb')
